- _layouts/default.html
- バージョンを v5.6.3 -> v5.12.0 に
- ブランドアイコンしか使用していないためallではなくbrandsを使用するように
> FontAwesomeのバージョン及びbrandsのみ使用するように修正

- css/index.css
グラデーション部分の青赤を反転し、テーマカラーに寄せました。
赤
`#de7072`
青
`#7995f7`
それぞれ、 [upd8 の宣材写真](https://upd8.jp/uploadimage/2018/05/omesis_up02.png)からピックしました
変更後
> グラデーションのカラーをテーマカラーに寄せてみました

- css/index.css
ボタン・リンクにマウスオーバ時のエフェクトを追加
マウスオーバ時に反応がないと、PCで閲覧している人がリンクと認識できない為
> ボタン・リンクにマウスオーバ時のエフェクトを追加

- README.md
- __tests__/sample.test.ts
- jest.config.js
- package-lock.json
- package.json
- preact/test_sample.ts
- preact_build/test_sample.js
- yarn.lock
js用テストフレームワーク、JESTを導入しました。
`js`, `ts`, `tsx` ファイルに対してテストを書くことができます。
これによってテストにて仕様の担保とTDD開発もすることができます。
サンプルケースとして、`preact` 内に `test_sample.tsx`, `__tests__` 内に `sample.test.ts` があります
> テストフレームワーク JEST追加

- alpha.html
- index.html
- 隠しリンクの位置がモデル表示している部分より上に来ていたので画面最下部になるよう修正。
- ローカルで表示されていなかったので見落としたため。
- また、隠しページからのシェアの場合はURLを抜くようにした
五月雨で申し訳ない！
> 隠しリンクの表示位置修正

- Dockerfile
コンテナ内のルートディレクトリにアプリケーションファイルが展開されていたので `WORKDIR` を利用するように変更しました
```
$ docker-compose exec omegasisters-webpage ls             
404.html              images                proc              
Dockerfile            index.html            root              
README.md             index.js              run               
__tests__             jest.config.js        sbin              
alpha.html            lib                   server.js         
assets                manifest.webmanifest  srv               
bin                   media                 sw.js             
css                   mnt                   sys               
dev                   node_modules          tmp               
docker-compose.yml    opt                   tsconfig.json     
dotnet                package-lock.json …
```
> Docker起動時のWORKDIRを指定

- Dockerfile
Dockerfileの最初で `package.json` `yarn.lock` をコピーし、`yarn` 実行する事により、nodeパッケージ内容に変更がない場合は `yarn` をskip出来るようにしました。
Dockerfileを変更するPRが既に出ていたのでそちら (#107) をベースにコミットを積みました。 #107 を先にマージしてください。
> Cache node packages on docker

- package.json
`yarn install`した際にwarningが出て気になるので、package.jsonにlicenseフィールドを追加し、`UNLICENSED`に設定しました。
ついでに、privateフィールドも追加し`true`に設定しました。
> Finally, if you do not wish to grant others the right to use a private or unpublished package under any terms:
> 
> ```
> { "license": "UNLICENSED" }
> ```
> Consider also setting "private": true to prevent accidental publication.
> https://docs.npmjs.com/files/package.json#license
publicリポジトリでみんながいじってるしUNLICENSEDで良いのかちょっと気になるけど、このコードを利用してみんながホームページを公開する想定では無いと思うので。
> package.jsonに設定を追加。license: UNLICENSED, private: true

- assets/js/ytplaylist.js
- css/index.css
マウスホバー時にタイトルが見れるといいなと思ったので入れてみました。
[![Image from Gyazo](https://i.gyazo.com/1214bd119aace854794decbd1d352db3.gif)](https://gyazo.com/1214bd119aace854794decbd1d352db3)
`npm start`で動作確認しました
マウスホバーに関してなのでPCのみで動きます（スマホだとタップ後にタイトルが出てくるかも？）
レイアウトが崩れに関してだけスマホもchrome dev toolで確認しています。
> 初心者向けすごい面白い動画のリストに、マウスホバーでタイトル表示

- .github/workflows/test.yml
yarnのtestをGitHub ActionsのCIで回すように変更しました🐧
参考資料
[GitHub Jest runner](https://github.com/marketplace/actions/run-jest)
> yarn CIの追加

- css/index.css
- スティッキーヘッダー部分を考慮してスクロールするように修正
ヘッダー部のリンクをクリックしてスクロールするとき、スティッキーヘッダー部分がかぶさってスクロールされてしまうのを修正しました。
> ヘッダーリンクでのスクロール時のヘッダーかぶりを修正

- assets/css/index.css
モバイルで「⭐【初心者向け】すごい面白い動画」にある次の動画、前の動画を表示するためボタンをタップした時に、ボタンのアウトラインが表示されてしまっているため表示しないようにしました。
PC版Safari、Chrome、モバイルのSafari、Chromeで確認済みです。
> モバイルで動画一覧の左右のボタンをタップした時に、アウトラインを表示しないようにする

- assets/css/index.css
- index.html
おめがってるー!?を動画の字幕風にしてみました。
動画の様に2重のアウトラインは頑張ってみたけど実現できなかったので、白の縁取りのみです。
アウトラインで字を潰さない為、元よりテキストサイズも大きくなってます。
* Pros
* インパクトがある。
* 動画に似せたスタイルにできる。
* Cons
* オシャレ感が減る。
* Google FontsでM+PLUS+1p:900を追加したので、その分通信量が増える。
PRを出した理由は、代表的なセリフが動画と同じ見た目になったらいいなと思ったからです。
まったく同じという所まではやりきれなかったですが、どうでしょうか？
少なくとも変な見た目ではない所までは、持って行けたかなと思ってはいるんですが、自分では目が慣れてしまって違和感に気が付けなくなっているかもです。
なお、カラーコードは https://youtu.be/DChL3IayER0?t=2 からスポイトツールで採取しました。
> おめがってるー!?を動画の字幕風にしてみた

- assets/css/index.css
おめが診断の結果をモバイルで表示すると、「診断結果」の文字が左に寄っていて不自然だったので中央寄せしました。（詳しくは添付画像を参照）
診断結果ページはおめがレイ、おめがリオ、うんちゃんの3ページでそれぞれ画像のように
中央寄せされます。
その他影響のあるおめシスのトップページとあるふぁブラザーズのトップページも含め、
PC版とモバイル版のSafariで表示が崩れないことを確認済みです。
> 診断結果ページのタイトルを中央寄せにする

- assets/css/sindan.css
> 診断ページの余白を調整

- assets/css/index.css
- assets/js/navbar.js
下記問題を修正しました。
1. モバイルの状態でΩをクリックしてメニューを表示
2. ウィンドウサイズを変更する
3. メニューが閉じられるが開閉ボタンは逆Ωのままで元に戻らなない
4. これ以降ボタンの向きとメニューの状態が逆になってしまう
ref. https://github.com/omegasisters/homepage/issues/245
ボタンの向きの変更はボタンクリック時/メニューボタンクリック時にJSでCSSのクラス名をtoggleする操作で実装されていましたが、メニューには [drawer.js](https://git.blivesta.com/drawer/)が使われており、このライブラリは`<body>`にメニュー表示状態を `.drawer-close`, `.drawer-open` のように与えます。
ですので、JSでCSSのクラス名を操作するのではなく、CSSで `.drawer-open` クラスが付いている時にΩボタンが `rotate(180deg)` になる指定にしておけば、メニューの状態とボタンの向きを同期させることができます。
CSSのクラスの変更があり、アニメーションが発生するので Event の `$('.drawer').on('drawer.closed', function(){});` を使うよりはアニメーションのテンポが遅れるということはないかと思いますが、一応実装者の @Iwaide …
> :cat2: :dash: モバイル ドロワーのメニュー開閉ボタンの向きをメニューの状態に合わせます

- assets/css/index.css
- preact/sindan/SindanApp.tsx
おめが診断ページからホームページに戻りたい時に遷移ボタンがあるとユーザーに優しいかと思いホームページのトップにあるうんちゃんを診断ページにも追加しました。
うんちゃんをクリックするとホームページに戻ります。
おめが診断をはじめるとうんちゃんは非表示になります。最後まで診断をやりきってもらうため。
- おまけ
作業中に金のうんちゃんが出てテンション上がりました💩！
> おめが診断ページにも右下にうんちゃん追加💩

- .vscode/cspell.json
code spell checkerで `omesis` がスペルミス扱いになってしまうという現象がありました。
詳しくは #330 に記載しました。
https://github.com/omegasisters/homepage/issues/330
`.vscode` フォルダに設定ファイル `cspell.json` を追加することで解決しました。
- おまけ
> code spell checkerで `omesis` がスペルミス扱いにならないようにしました

- index.html
- pages/alpha.html
スイッチの位置がが下過ぎて一部Android端末だと選択肢を選べなくなってた。
なので、スイッチの位置を一番上に持ってきた。
ついでにアルブラのページの分も直しました。
- おまけ
> 言語スイッチの位置変更

- assets/css/index.css
https://github.com/omegasisters/homepage/issues/342
画面サイズによってはヘッダーが2列になってしまう問題を取り急ぎ修正しました。
あんまりきれいじゃないですが…小さくなりすぎないように徐々に文字サイズを小さくして対応してます。
そもそもヘッダーメニューが多すぎ問題な気も。。
- おまけ
> 画面サイズによってヘッダーが2列になってしまうのを修正

- assets/css/index.css
スマホサイズ時のナビメニューをPCサイズのヘッダーメニューと同等の暗さにすることでナビメニューを開いていることを視覚的にわかりやすくする
- おまけ
> drawer-navの背景色を暗くする

- .prettierignore
- pages/alpha.html
`yarn test` によって自動生成された`coverage/test_sample.ts.html` が `yarn format` に引っかかり常にエラーが発生します。`coverage` 以下は自動生成されるものであり、`gitignore`にも指定されているのでフォーマット対象から除外して対処します。
- おまけ
> coverageをフォーマット対象から除外する

- assets/css/index.css
- index.html
埋め込んだTwitter widgetの幅が固定されていて画面サイズが小さい時に横スクロールが発生する状態になっていたのを画面サイズ内に収まるように修正しました。
合わせて少し小さめの画面サイズでも 2 column で表示されるように調整しました。
**before <--------> after :rabbit:**  
- おまけ
> :cat2::dash: モバイルサイズでTwitter widgetがはみ出していた問題を修正しました

- assets/css/index.css
- assets/i18n/resource.json
- index.html
おめシス人気投票へのリンクを一時的に追加しました。
- おまけ
> おめシス人気投票へのリンクを一時的に追加

- assets/css/index.css
メニュー項目が増え特にモバイル時にフォントサイズが余りにも小さくなってしまっていたため、文字サイズを調整しました。
合わせてメニューの文字サイズの調整が複雑になCSSになってしまっていたので、PCサイズではメニューが固定幅になるまではでは `vw`  でフォントサイズをレスポンシブになるように指定しました。
> `vw`: 1% of the viewport's width  
> https://developer.mozilla.org/ja/docs/Learn/CSS/Building_blocks/Values_and_units
※ `z-index` を調整してあるので、Ωメニュー開閉ボタンタップ可能です
- おまけ
- ~~[ ] Pull Request …
> グローバルメニューのフォントサイズを調整しました。

- README.en.md
- README.md
- webpack.config.js
開発サーバー (`localhost:8080`) で 【初心者向け】すごい面白い動画 の json が読み込まれず、表示されない問題を修正しました。
https://github.com/omegasisters/homepage/blob/939b5a8abb878f716a1da09f76bbaceb3185e9fc/assets/js/ytplaylist.js#L2
開発サーバーの root は `/homepage` ではなく、動画リストの読み込みは `/homepage` のパスで fetch していたためにパスが異なり json が読み込めていない状態となっていました。
そこで下記修正を行いました。
副作用として、本サイトと同様に `/homepage` でパスを指定することができるようになりました :tada:
1. `yarn start` で起動する dev server の root を実際のサイトど同じ `/homepage` に変更
1. `yarn start` でデフォルトで `localhost:8080/homepage/` が開くように変更
ref. https://github.com/omegasisters/homepage/issues/374 
fixed https://github.com/omegasisters/homepage/issues/231
cf. https://webpack.js.org/configuration/dev-server/#devservercontentbasepublicpath
- `git …
> :cactus: webpack dev-server の root を /homepage にしました

- index.html
- pages/pass200000sss.html
> [更新] 22万登録者

- package.json
- yarn.lock
`start:docker` のコマンドで`ts:watch`を実行していましたが
どこかのタイミングで`ts:watch`が消されてしまっており実行時にエラーが発生してました。
→ `serve`と並列で実行されていたので今まで問題にはならなかった
コンテナ内でwatchする必要もないのでこのまま削除してます。
それに伴い`concurrently`が利用されなくなるので削除しました。
- おまけ
なし
> `npm run start:docker` でエラーが発生していたので修正
