omegasisters/homepage

index.html
=> 文中の URL をハイパーリンクに変更

index.html
=> headとtitleを追加

_pages/index.html
おめシスのホームページのTwitter共有リンクを配置しました
=> おめシスはいいぞってTwitterに共有できるリンクを追加したよ！

_pages/404.html, css/index.scss
よろしくお願いします🙌
- URLを修正
- フォントにKosugi Maruを使用するように
- 現状情報量が少ないためフォントサイズを大きめに
- scssの整理
=> URL, スタイルを修正

_layouts/default.html, _pages/index.html, css/index.scss
=> YouTube と Twitter のアイコンを追加

_layouts/default.html
normalize.css を最新版に更新しました
7.0.0 => 8.0.1
=> normalize.css の更新

_pages/index.html
Twitter用の設定を追加
アカウントはお姉ちゃんなのでレイちゃんの方にしました
=> Twitter用のOGP設定を追加

_layouts/default.html, _pages/index.html
=> TwitterのOGPの修正

css/index.scss
=> スマートフォンに最適化

_layouts/default.html
`<meta charset="UTF-8" />`が重複していたので片方削除しました
=> 重複していたmetaタグを削除

_pages/index.html, css/index.scss
=> Twitterのプロフィール画像, IDを追加

_pages/index.html
デプロイすると動かなくなってるみたいなので応急処置的な修正をしました。
これで多分ちゃんと表示されるかな？
=> おとひめビュワーのバグ修正

_pages/index.html, css/index.scss
=> シェアリンクをボタンにした

css/index.scss
=> Twitterリンク部分のスタイルの修正

_pages/index.html
=> おとひめビュワーのデザイン修正

_pages/index.html, assets/js/App.jsx
=> 外部サイトのリンクは別タブで開くように変更しました

_pages/index.html
どんな問題があるかは以下の Google Developers の記事に書かれています
[サイトで rel="noopener" を使用して外部アンカーを開く](https://developers.google.com/web/tools/lighthouse/audits/noopener?hl=ja)
=> 念のため外部サイトを開くときの脆弱性対策をした

css/index.css
タイトルの文字が読みにくかったので、以下を変更してみました。いかがでしょうか？
- 背景にブラーをかける
- ヘッダーテキストに影をつける(お二人のテーマカラーの赤と青で両斜め下に入れました)
before
[![Image from Gyazo](https://i.gyazo.com/7c070a931b902f1025f5695ebd997e5f.png)](https://gyazo.com/7c070a931b902f1025f5695ebd997e5f)
after
[![Image from Gyazo](https://i.gyazo.com/b2f0410b9af46838fdcda713bd8dac6e.png)](https://gyazo.com/b2f0410b9af46838fdcda713bd8dac6e)
blurの量、色の調整等、センスのある方いらっしゃったらぜひ変更してください！！！
推しにプルリクエストが送れる時代になったんですね…
=> タイトルの読みやすさのために、背景にブラーを追加 & ヘッダテキストにtext-shadowを追加

css/index.css, index.html
=> うんちゃんを追加したよ！

README.md
log:
~/dev/homepage$ python3 -m http.server -d ..
usage: server.py [-h] [--cgi] [--bind ADDRESS] [port]
server.py: error: argument port: invalid int value: '..'
~/dev/homepage$ cd ..
~/dev$ python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 ...
=> local web サーバの起動に失敗する場合の対処方法を追記

images/ray.svg, images/rio.svg
半ば素材供養のような感じになりますが動画からsvg化しましたので取り急ぎ
#39 が追加されたのでそっちにから引っ張ってきたさ…
=> 背景動画のsvg素材追加

README.md, css/index.css, package.json, yarn.lock
=> Prettier導入

css/index.css
=> ヘッダーが微妙に横に伸びて横スクロールバーが出てしまう問題の修正

css/index.css, index.html
IDの部分だけリンクにしてたのを黒い部分全体リンクにしました！
=> Twitterリンクがidだけでなく黒い部分のどこを触ってもジャンプできるように

index.html
=> ページ右下のうんちゃんクリックでページトップに戻る

index.html
=> Link追加 : ⭐【初心者向け】すごい面白い動画

index.html
=> OGPの画像パスを絶対パスにした

index.html
=> アクセシビリティを改善

css/index.css, index.html
- ヘッダーによみがなを追加しました！
- Prettierを実行しました！
=> ヘッダーによみがなを追加

README.md
Elixirを使ったローカルサーバーの起動方法を追加しました。
=> Elixirでもローカルサーバーを立てる

css/index.css, index.html
pixivFANBOXへのリンクの追加とContactリンクの追加
~~伴うFont Awesome のALL化 #13~~
pixivFANBOX :https://www.pixiv.net/fanbox/creator/31737746
Contact : https://upd8.jp/contact_us/index.html
=> FANBOX/Contact リンクの追加

css/index.css
=> Fix-FANBOX/Contact リンクの追加

css/index.css, index.html
Heroの背景の端が白くなっているのが気になったので修正しました。
after
=> Topの端が白くなっているのを修正

assets/js/lazyload.js, assets/js/ytplaylist.js, assets/playlists/PLjUYRJfqz5WuCvIcDw6a_maOwZN7ic4ja.json, css/index.css, index.html
- `introduction` の所に、`すごい面白い動画`のプレイリストに入っている動画のサムネイルを横スクロール形式でおいてみました。ウェブサイトを訪れた人がすぐに動画に飛びやすくなると思います。
- lazyloadを後から動かせるように関数にしました
cssだけ作ってjsを作ろうとしていた所YouTube APIにトークン必須という事に気がついて応急処置で `assets/playlists` にプレイリストのデータを置いています😰
=> `すごい面白い動画` プレイリストをHP上にリストアップ

css/index.css, index.html
おめシスが良いことをハッシュタグで伝えられるように修正
ホームページということを伝えるより、つぶやきでは愛を伝えたい為
https://github.com/omegasisters/homepage/pull/72 の続きで修正してしまったので、先に https://github.com/omegasisters/homepage/pull/72 を見てもらえると嬉しいです。
=> おめシスが良いことをハッシュタグで伝えられるように修正

.gitignore, README.md, dotnet/Program.cs, dotnet/Properties/appsettings.Development.json, dotnet/Properties/launchSettings.json, dotnet/Startup.cs, dotnet/appsettings.json, dotnet/homepage.csproj
=> .NET Coreを使用した開発環境の追加

index.html
- GitHubアイコンを追加
- デザインの統一感が上がります
- GitHubの視認性があがります
=> GitHubアイコンを追加

css/index.css, dotnet/Properties/launchSettings.json
- 再生リストのスタイルを修正しました！
- 上のブロックからもう少し間隔を開けるように
- 動画サムネイルの間隔を修正
- 横スクロールバーを装飾 (Chromeのみ?)
- prettierを実行しました！
=> 再生リストのスタイルを修正

index.html
URLにパラメータを追加して、お問い合わせ対象のチャンネル名に自動でおめシスのチャンネルが選択されている状態にした。
- 変更前
- https://upd8.jp/contact_us/index.html
- 変更後
- https://upd8.jp/contact_us/index.html?sc=%E3%81%8A%E3%82%81%E3%81%8C%E3%82%B7%E3%82%B9%E3%82%BF%E3%83%BC%E3%82%BA%20[%CE%A9%20Sisters]
=> お問い合わせ用URLを更新

assets/js/scroll-to-top.js, index.html
- カーソルをかざしたら `トップに戻る` が表示されるようにしました！
- #55: うんちゃんのスクロール時にユーザーが止めた場合それ以上スクロールしないようにしました！
=> うんちゃんスクロールボタンを修正

css/index.css, index.html
HPなのにおめシスとは何なのかに関する記載がなかったので追加
なお、`ホームページです!`の箇所と重複するため、 `バーチャル双子ユーチューバーのおめがシスターズ。` はトルツメしました。
via https://upd8.jp/virtual_talent/%E3%81%8A%E3%82%81%E3%81%8C%E3%82%B7%E3%82%B9%E3%82%BF%E3%83%BC%E3%82%BA.html
=> 各種リンクの上にupd8に記載のあった紹介文を追加

index.html
=> JSON-LD構造化データのimageをogpの画像に合わせる

Dockerfile, README.md
`docker` 環境があれば、ローカルにnode等が無くても確認できるようになります
Dockerのインストールについては各OS等で異なると思うので `README.md` からは省略しています。
=> Dockerfileを追加

css/index.css, index.html
- Twitter profileをホバーしたときの色をレイちゃん/リオちゃんカラーに変更しました
=> おめシスのTwitterプロフィールのhoverカラーを変更

css/index.css
=> 隠しリンクにアニメーション追加

README.md
readmeが「Tips」の文字だらけだったので見出しを整理しました
=> readmeのtipなどの見出し整理

css/index.css, index.html
うんちゃんスクロールボタンをマウスオーバーすると、吹き出しを出すようにしました
=> うんちゃんスクロールボタンをマウスオーバーすると吹き出しを出すように

README.md, docker-compose.yml
`docker-compose.yml` を追加し、`README.md` に起動方法を記載しました。
`docker run` での起動方法よりも必要コマンドが少なくなります。
既存の `Dockerfile` を用いています。
=> docker-compose.ymlを追加

docker-compose.yml
- `version` の修正
- `ports` の追加
[こちらのプルリクエスト](https://github.com/omegasisters/homepage/pull/104)作成時にコミット忘れがありました。すみません…
=> docker-compose.yml コミット忘れに伴う修正

index.html
head内にコメントアウトの状態で、でっかいunchanのAAを追加しました。
確認する際はデベロッパーツールで幅を大きくしてもらえると良い感じに表示されます。
chromeでの動作環境確認済み(十分な幅があればちゃんと表示される)
firefoxでの動作環境確認済み(幅が合えば)
safariでの動作環境確認済み(幅が合えば)
=> head unchanAA add

README.md
- Python編の見出しを追加
- 文言配置を整理
Python編と明示的に書くことでよりわかりやすくなると思います。
=> READMEのPythonの例を修正

css/index.css, index.html
- GoogleのMaterial アイコンの読み込みを追加しました
- ロード時の画面に下へのスクロールを示す矢印を追加しました
- 「下方向にスクロールすればコンテンツが見えるよ」ということが伝わるかなと、上下に揺れるアニメーションもつけて主張しているつもりです
=> added navigation arrow

css/index.css
- スマホでのtwitterリンクのスタイルの問題を修正しました！(間隔など)
- prettierを実行しました！
=> スマホでのtwitterリンクのスタイルの問題を修正

css/index.css, index.html
おめシスの二人が見切れていたので3Dモデルをリンクセクションから分離しました。
=> 3Dモデルをセクション分け

css/index.css, index.html
=> イントロの背景を変えました

css/index.css, index.html
**introduction section**
マージンと、 ビデオサイズの調整
**links section**
画面サイズによっては、御御足が見えなかったのが残念だったので。
**修正前**
**修正後**
=> introduction セクションと、links セクションのマージンなどの調整

homepage/web_modules/import-map.json, homepage/web_modules/three/examples/jsm/webxr/VRButton.js, package.json, preact/App.tsx, preact/three/rotate.ts, preact/three/scene.ts, preact/three/viewer.ts, preact_build/App.js, preact_build/three/rotate.js, preact_build/three/scene.js, preact_build/three/viewer.js, web_modules/import-map.json, web_modules/three/examples/jsm/webxr/VRButton.js
OculusQuest：OculusBrowser
PCVR：FireFox
環境で3DモデルをVRで見られるようにした
=> 3DモデルビュワーのWebVR対応

index.html
表題の通り、お二人のTwitterを埋め込んだ。
- 広い場合
- 狭い場合
--
埋め込み用の設定
https://publish.twitter.com/
```
height: 500
width: 300
look: dark
lang: auto
Opt-out of tailoring Twitter: true
```
https://publish.twitter.com/?dnt=1&maxheight=500&maxwidth=300&query=https%3A%2F%2Ftwitter.com%2Fomesis_ray&theme=dark&widget=Timeline
https://publish.twitter.com/?dnt=1&maxheight=500&maxwidth=300&query=https%3A%2F%2Ftwitter.com%2Fomesis_rio&theme=dark&widget=Timeline
=> おめシスtwitterを埋め込み ref #117

css/index.css
#127  変更内容
リンクによってhoverがあったりなかったりするのが気になったため。
=> リンクのhoverをデフォルトにしてみました

css/alpha.css
=> 隠しページのタイトルが表示されていなかったので修正 fix #128

alpha.html, css/alpha.css
=> 隠しページの表示をindexに合わせる

css/alpha.css
=> SPなど画角が狭い端末の場合、隠しページ画面下部の表示を変更する

css/index.css, index.html
- twitterリンク下に持ってくるように
- それに伴いtwitterリンクを常に横並びにした
- 背景をそれぞれの色にした（ただ配色が微妙になってしまったような気がするので誰か修正していただけると助かります😰）
- prettierを実行
=> twitter embedを修正

css/index.css, index.html
=> twitter embed をdarkに戻す

index.html
pixivFANBOX は固有名詞であり(一般的な単語として fan box があるわけではなく)、ここに空白を入れるのは不自然である為、取ります。
=> s/FAN BOX/FANBOX/

css/index.css, index.html, preact/Music.tsx
各項目にジャンプできるおなじみのヘッダです。
項目をどのグループで分けるか、どこへのリンクを用意するかなどは一考の余地あり。
ハンバーガーにして折りたたんで、空いたスペースにロゴやうんちを表示するのもあり？
ひとまず叩き台として！
=> 一番上にヘッダをつけたよ！

alpha.html, assets/js/ytplaylist_alpha.js, assets/playlists/alphaList.json, index.html
あるふぁブラザーズのページにもindexのJSを流用して動画一覧を差し込みました！
プレイリストが無く、チャンネル動画も少なかったので、投稿動画一覧です。
[ToDo]：タイトルや文言もあるふぁブラザーズ用に合わせた方がいいかも
ついでに、YouTubeチャンネルリンクを修正して飛んだ際に、チャンネル登録画面が出るようにしました。
=> あるふぁブラザーズのページにも動画一覧を足したよ！

index.html
ページトップの 下向き矢印アイコン に `おめシスって？` へのページ内リンクを設定しました。
押すと下にスクロールしたような感じになります。
=> ページトップの下向き矢印アイコンにページ内リンクを設定

assets/js/navbar.js, assets/playlists/alphaList.json, css/index.css, index.html
- ナビゲーションバーのスタイルをそれっぽくしてみました。
- prettierを実行しました。
=> ナビゲーションのスタイルを修正

css/index.css, index.html
うんちゃんをクリックしてスクロールができなくなってたので修正しました
=> スクロールができないバグを修正

assets/js/ytplaylist.js
あるふぁブラザーズのページに表示されるプレイリストをあるふぁブラザーズのものに変更
=> #170 あるふぁブラザーズのプレイリストに変更

index.html
Fix [【不具合】ytplaylist\.jsでシンタックスエラー · Issue \#169 · omegasisters/homepage](https://github.com/omegasisters/homepage/issues/169)
Fix [【不具合】lazyload\.jsでSyntaxError · Issue \#168 · omegasisters/homepage](https://github.com/omegasisters/homepage/issues/168)
ytplaylist.js, lazyload.jsが2回読み込まれていたため、SyntaxErrorが発生していました。
e.g.
```
ytplaylist.js:1 Uncaught SyntaxError: Identifier 'loadPlayList' has already been declared
at ytplaylist.js:1
```
https://github.com/Iwaide/homepage/blob/630119e5f3f955fb4fcfa8da44e4f1ae561ebb26/index.html#L400-L404
の一回で読み込まれるよう変更しました。
| before | after |
| --- | --- |
| …
=> Remove duplicated script loading

README.md
#143 に対する対応です。
PHP編のセクションにのみ書かれていた他の端末からの接続方法を共通化しました。
修正内容について意見がもらえると嬉しいです。
速攻マージしないでほしいためDraft Pull Requestにしています。
=> 他のデバイスから確認する方法の説明を共通化

css/index.css, index.html
=> #163 youtubeチャンネルリンクを上の方にも追加

assets/js/ytplaylist.js, assets/playlists/alphaList.json
あるブラの動画一覧の中でリンクが飛べなくなっているものがあったので削除して、読み込み元jsにコメントで動画一覧URLを追加しました。
=> 動画一覧の飛べない動画を削除

assets/js/navbar.js, css/index.css, index.html
- モバイル用のハンバーガーメニューを追加しました
Drawerというプラグインを使用しました。
[Drawer \- Flexible drawer menu using jQuery, iScroll and CSS\.](https://git.blivesta.com/drawer/)
- セマンティックなHTMLになるよう、idにheaderがついたdivタグをheaderタグに書き直すなどしました。
右上のアイコン、連打されるとクルクル回ってしまうので、連打防止かDrawerにうまくフックできるようにしたい…
変更箇所が大きいように見えますが、インデント修正に伴うものなので、Hide Whitespace changes していただければと思います 🙇
=> モバイル用のヘッダーメニューを追加

alpha.html, css/alpha.css
おめシスからあるブラには飛べるけど、あるブラからおめシスに飛べなかったからリンク追加
- 😭 やったけど、触ってないファイルが整形されたので、差分から外しました。
- `animation` に `omega-noise` を使ってるけど `alpha-noise` 作った方がいいかな。。
=> あるブラからおめシスに飛ぶリンクを追加

documents/environment/node.md, documents/environment/python.md
ポート番号が間違っていたので修正。
多分、環境依存ではないと思う。
=> documents/environment/node.md を少しだけ修正 (ポート番号)

documents/environment/python.md
github のプルリクエストの仕様を間違って理解していたために、
意図せずマージされてしまった以下のコミット ( ae7ddfc - #192 の一部) を修正。
commit ae7ddfc0d8b5cda345b49e14b9f6f68eb29bcaca
Author: hirune4791dev <hirune4791.dev@gmail.com>
Date:   Wed Dec 25 14:27:48 2019 +0900
add info related to python version
=> documents/environment/python.md へ、Python のバージョン依存情報の追記

alpha.html, assets/js/ytplaylist.js, css/index.css, index.html
スライダーをswiperに変更し狭い画角の場合のスタイルを調整
出来る限りjQueryからの脱却
=> slickをswiperに変更

css/index.css
ハンバーガーメニュー的なやつにボーダーを追加してタップ出来る感を出してみた。
=> ヘッダーメニューアイコンにボーダーを追加

alpha.html, css/alpha.css
indexと同じようにヘッダーを追加した
-x何らかの理由で本番に取り込まれるまで確認できない場合はその旨を補足に記載する。
#201 が通ったらドラフトから正式にPRする
=> 隠しページにヘッダーを追加

README.en.md, README.md, README.zh_hans.md
Fix [【要望・提案】README等の多言語対応 · Issue \#196 · omegasisters/homepage](https://github.com/omegasisters/homepage/issues/196)
Fix  [这是啥 老铁们 为啥这个项目会排在前面 · Issue \#194 · omegasisters/homepage](https://github.com/omegasisters/homepage/issues/194)
Fix [【不具合】このプロジェクトは何がため。 · Issue \#199 · omegasisters/homepage](https://github.com/omegasisters/homepage/issues/199)
READMEに英語と中国語を追加しました。
みんながもっと気軽にコントリビュートできるように、あえてGoogle翻訳ほぼそのままを持ってきています。
叩き台さえ用意すれば勝手に良くなっていくと信じています 🙏 
他言語のREADMEファイルの命名は[hamukazu/lets\-get\-arrested: This project is intended to protest against the police in Japan](https://github.com/hamukazu/lets-get-arrested)を拝借しました。
=> READMEに英語版、簡体中国語版を追加

alpha.html
あるブラページにて「⭐【初心者向け】すごい面白い動画」の文字が二つあり，ナビゲーションもずれていたので，おめシスページと同様の形に修正しました．
修正前
修正後
=> おすすめ動画のタイトルが二つあったので修正

README.zh_hans.md
=> Fixed the Chinese readme

index.html
LINE STOREへのリンクを追加しました。
これでおめシスにマネーが！？
=> add LINE STORE link

css/index.css
https://github.com/omegasisters/homepage/issues/219
のワークアラウンド
iphone8 + chrome&safariで確認済み
=> ハンバーガーメニューのアイコンが切れないようにする

documents/environment/python.md
#185 の対応
python.md の記述をシンプルにしました。
特になし
=> ローカルプレビュー Python編のドキュメント修正

assets/js/lucky_rayrio.js, assets/js/navbar.js
個人的に理解しづらいと思った箇所、無駄であると思った箇所をいくつか修正しました。
`assets/js/navbar.js` は defer 属性付きでロードされるため必ず HTML のパースが完了した時点で実行されるので `$(document).ready` は不要です。
=> JavaScript のリファクタリング

pages/sindan_ray.html, pages/sindan_rio.html, pages/sindan_unchan.html
* `/` に設定されて 404 になっていたので `/homepage/` に直しました
* 自動生成のファイルかどうかよくわかってないのでもしそうならご指摘願います
* `npm run` した環境だと `/homepage/` に移動すると逆に壊れてしまうのでその辺りも知見ある方アドバイスいただきたいです
=> 診断結果ページの "ホームページへ" リンクを修正しました

alpha.html, index.html, pages/sindan_ray.html, pages/sindan_rio.html, pages/sindan_unchan.html, sindan.html, synchronity.html
「【不具合】ソースコード中の Youtuber 表記について #232 」対応
=> Fix typo for Youtuber to YouTuber

css/sindan.css
おめが診断のページをPCで閲覧した際、ボタン上のカーソルをリンクカーソルにして、
クリックできる感を出してみました。
* before
* after
=> おめが診断のボタンが押せることをわかりやすくする

assets/js/lucky_rayrio.js
#151 で議題に上がった、下記内容に対応するため、サイト初回訪問時にラッキーレリオちゃんを表示しないように変更。
> あと、予定は未定なのですが、現状では折角"幸運のレリオちゃん"を引き当てても、気づかずにスルーしている人が多くいそうなので、その辺対策できればなと思っています。
サイト訪問2回目以降に表示できることは、確率を1%👉100%に変更して確認済みです。
=> Change show condition of Lucky-rayrio

package.json
`$ yarn build` コマンドが使用できなくなっていたので、使用できるように変更
yarn warnに従い、 `--scripts-prepend-node-path` オプションを追加
=> `$ yarn build` コマンドが使用できなくなっていたので、使用できるように変更

index.html
企業担当者がおめがシスターズにコンタクトを取ろうとした際、「お問い合わせ」を見つけやすいように変更（他Vtuber公式サイトを見てもそうなっていた）
マネー💵が変わるはず！！
=> ナビゲーションバーに「お問い合わせ」を追加

README.zh_hans.md
Only the Chinese README file has been changed.
Bugfix:
- Fix misuse of Chinese parentheses in markdown hyperlinks
- Fix misuse of Chinese colon marks in hyperlinks
Enhancement:
- Add space between hyperlinks and texts for better display
- Add space between Chinese and non-Chinese characters for better display
Since this is only a change in the markdown files, prettier is not run.
=> Fix bugs and enhance display in Chinese README

pages/sindan.html
=> 診断ページのスクリプトのパス修正

pages/alpha.html, pages/sindan_ray.html, pages/sindan_rio.html, pages/sindan_unchan.html
ホームページ(index.js)へのパスが、画面ごとに異なっていました。
おめが診断ページ、シンクロ二ティページ、隠しサイトページでパスの設定方法が別れていたので、
シンクロ二ティページで使われていた'/homepage'に統一しました。
=> ホームページへのパスを統一

index.html
言語切り替え用のスイッチャーについて、以下の変更を行った。
- ヘッダーと同様、スクロールした場合でも上部に固定されるように変更
- 軽い位置調整
=> 言語切り替え用のスイッチャーを画面上部に固定

assets/css/index.css
- ファーストビューの「おめシスって？」の画面に移動するアイコンをモバイルでクリックした時、青い四角が表示されていたものを表示されなくしました(GIF参照)
=> モバイルでのタップ時の青四角を表示しないように

pages/contributors.html
=> コントリビュータ一覧ページの追加

README.en.md, README.md, documents/README.md
The text is easier to read
README.mdを見やすく文章整理（Japanese & English）
- 1行に情報量が多かったため、1文1義に変更
- ユーザーが何ができるかを明文化
- document/ にREADME.mdを追加
中国語は、私が読めないので編集していません。
=> README.mdを見やすく文章整理（Japanese & English）

README.en.md, README.md
=> Add link to README image

assets/js/ytplaylist.js
youtubeの動画リストをjsonファイルから取得しているのですが、
ファイルの指定を相対パスからルートパスに変更します。
(呼び出すページのフォルダ階層に関係なく動画リストが表示されるようになります)
=> 隠しサイトで動画リストが表示されない件を解消します

assets/js/ytplaylist.js
https://github.com/omegasisters/homepage/issues/267 でのバグ対応
=> Fix playlist path

.vscode/launch.json
vscodeのデバッグモード設定ファイルであるlanch.jsonのタイポを修正
=> Fix lanch.json typo

assets/js/ytplaylist.js
インデックスページの再生リストの細かなリファクタリングを行いました。機能的な変更はありません。
- ?alphaを指定してインデックスページを開いても再生リストが変わらないように変更
- Google ChromeのAuditsで報告されている問題の修正
- コードの細かな調整
=> 再生リストの細かなリファクタリング

assets/css/index.css, index.html, pages/synchronity.html
- シンクロニティのページでスムーズスクロールが機能するように修正
- Google ChromeのAuditsで報告される問題の修正
- コードの細かな修正
=> ページの先頭に戻る（うんちゃん）の細かなリファクタリング

assets/css/index.css, assets/js/lucky_rayrio.js
幸運のレリオちゃん出現時 (#151) のみ、画面右下のうんちゃんの色を特別色に変更する。
折角幸運のレリオちゃんを引いても、気づかれずにスルーされている可能性があるので、少しでも気づきやすいように。
コード上で発生確率を変更して、動作確認を実施。
=> 幸運のレリオちゃん出現時 (#151) のみ、うんちゃんの色を特別色に変更する。

index.html
br要素名直後に空白がないことで、SP向けのbrタグが無効化されていたのを修正。
typoの修正。
該当部分についてSPで見た時に意図した改行が行われます。
　　FirefoxによるSPエミュレーションでは意図した改行が追加された事を確認済み。
　　但し、SP実機での動作は未確認。
　　1文字修正のため、実施しておりません。
　　2個目のチェックに記載。
=> typo修正(SP用改行)

.github/workflows/test.yml, README.en.md, README.md, README.zh_hans.md
- READMEバッジ追加（CI、Open issue追加）
- README微修正
=> Add CI badge

assets/i18n/resource.json, index.html
多言語対応が現在一部のみ対応されているので、ひとまずおめシスの説明文だけでも英語と中国語に対応させました。
=> 説明文の英語、中国語を追加

preact/sindan/SindanApp.tsx
SindanApp.tsxの型の付け方に気になる点があったので修正しました。
これで`catch(e)`の箇所以外のanyは撲滅しました。
一部`as`を使っている箇所がありますが、それは以下の理由によりです。
- `sindanQuestions.js`を読み込んでいるため仕方なく
- TypeScriptでのObjectのkeyの走査には良い感じ型が当たらない(?)
上の点については、`sindanQuestions.ts`を用意してそこに`SindanPoints`などを使ってデータの定義をするか、別途型定義ファイルを用意すれば回避できます。
下の点については、不明です。どなたか良い方法があればご教示ください。
=> SindanApp.tsxをより型安全にしました

.gitignore, jest.config.js
`yarn test` した時にcoverageフォルダが出来ます。その中のindex.htmlを見るとコードカバレッジを確認することが出来ます。
現状テストがないので、まだ必要ないかなと思います。
必要なければ、Closeで問題ないです。よろしくお願いします！
=> カバレッジレポートを導入

.dockerignore, Dockerfile
https://github.com/omegasisters/homepage/pull/109 で対応が入った状態では不完全なので、以下の通りに修正しました。
Dockerのキャッシュが効かないようになっていたので効くように修正しました。具体的には、ADD句ではキャッシュが効かないため、COPY句に変えています。
Dockerビルド時に.gitやローカルのnode_modulesを転送すると非常にサイズが大きくなってしまうので、転送しないように修正しました。
=> modify dockerfile

assets/i18n/resource.json, index.html
言語変更しても一部日本語のままな箇所があったので翻訳されるように対応しました。
とりあえずHTMLの部分だけで、3Dモデルの `回転停止` など（JSの部分）は対応できていません。
=> 英語・中国語の翻訳を追加

assets/i18n/resource.json, preact/hooks/useI18n.tsx, preact/i18n/i18n.ts, preact/main/Viewer.tsx
=> 3Dモデルビュワーの多言語対応

assets/i18n/resource.json
=> 中国語の内容を一部修正

.github/PULL_REQUEST_TEMPLATE.md
=> add master import method for fork source repository

preact/i18n/Switcher.tsx, preact/main/Music.tsx, preact/sindan/SindanApp.tsx
- preactでの動的処理部において、可視性、可読性、ソースの保守性向上のため下記の細かいリファクタを行った。
- preact/main/Music.tsx(歌ってみたシリーズ部)において、動画選択時の副作用的処理をEffectにまとめる
- preact/sindan/SindanApp.tsx(おめが診断部)において、診断開始判定処理に伴う副作用的処理をEffectにまとめる
- preact/i18n/Switcher.tsx(i18n部)、可読性向上のための分割代入に変更
- おまけ
=> Refactoring preact component.

index.html
取り急ぎ、サイト製作者について検証動画込みで追加してみました👍
https://github.com/omegasisters/homepage/issues/256, https://github.com/omegasisters/homepage/issues/278
- おまけ
CSS修正できる方がいると助かります🙏
=> Add contributers

assets/i18n/resource.json, index.html
=> 英語、中国語の翻訳を追加、少し修正

README.en.md, README.md, README.zh_hans.md, assets/i18n/resource.json, index.html
- 重複していたHTMLのidを変更
- README更新
- おまけ
=> Avoid duplicate HTML ids

assets/i18n/resource.json
* 英語部分で"singing musics"は不自然なので"singing songs"に修正しました。
(I felt a little queer about "singing musics", so I changed it to "singing songs".)
直訳すると「音楽を歌う」となっている部分を「歌を歌う」に変更したことにより、英語圏の人間によりおめシスの活動内容が違和感なく伝わるはずです。
- おまけ
１単語だけの修正なので特にありません。
=> 英語表記の不自然な部分を修正しました

assets/i18n/resource.json
=> ページの表示内容の幾つかのミスを修正

.github/workflows/deploy.yml
preactビルドの差分が無いとgit commit出来ずにCIが落ちていたので空コミットを許容するようにした。
- おまけ
=> GithubActionのエラー抑制

assets/css/index.css, index.html
結果動画の部分でうんちゃんがかぶってしまっていたのでかぶらないようにちょっと広げました。
もうちょいcssのマークアップなんとかしたい感ありますが一旦はこれで。
before
after
- おまけ
=> 結果動画部分でうんちゃんが被らないように修正

assets/i18n/resource.json, pages/alpha.html
あるブラのページに一部の表示内容の翻訳を追加してみました！
もしミスがあればご指摘ください！
- おまけ
=> あるブラのページに英語、中国語の翻訳を追加してみた

assets/i18n/resource.json, pages/alpha.html
先ほどのPRが出来ましたので、残りの部分も追加しました！
- おまけ
=> あるブラのページに英語、中国語の翻訳を追加

index.html
TOP ページのヘッダ部分に関して。
ページ表示直後、"製作者について" なのに、すぐに "製作者" に変わる。
どちらかに寄せるべきだが、 ヘッダ部としては "製作者について" は文字数が多いことと、他言語の表記との統一感から、 "製作者" 側に寄せました。
- おまけ
=> ヘッダ部分の "製作者について" を "製作者" に修正

assets/js/replace_history.js, index.html
スクロールしたときに、スクロールバーのURLが見ているセクションのものに変わります。
URLをコピペするときに便利。
- おまけ
=> Change url when scrolled.

assets/css/index.css, index.html
製作者セクションに、PR関連 tweet ２つを追加
- おまけ
#117
=> 製作者セクションに、PR関連tweet ２つを追加

index.html
=> コンソールに「おめがってるー！？」の挨拶追加

assets/css/index.css, assets/js/ytplaylist.js, index.html
特に画面幅狭い場合に関して、以下を調整。
* 製作者についてのツイートサイズ
* シンクロニティの画像サイズ
* すごい面白い動画のリスト
- おまけ
=> 続・画面幅が狭い場合の調整

assets/playlists/PLjUYRJfqz5WuCvIcDw6a_maOwZN7ic4ja.json
=> ⭐【初心者向け】すごい面白い動画のリストを更新

index.html
おめシス人気投票リンクの遷移先を #368 で追加された人気投票セクションに変更します。
関連 : #369
- おまけ
=> おめシス人気投票リンクの遷移先を変更

assets/css/index.css, assets/i18n/resource.json, index.html
うんちゃん(or ふきだし)をタップすると人気投票セクションへ移動するように期間限定で変更します。
代わりにヘッダーメニューに配置されている人気投票リンクは削除します。
詳細な経緯などは #369 を参照ください。
- おまけ
=> うんちゃんを人気投票セクションへのリンクに変更

assets/css/index.css
`min-width`と`max-width`が`64em`でダブっていたので，`max-width`を未満になるように`63.999em`に修正。
Issue: #379 
- おまけ
=> ブレイクポイントの値を修正しました

documents/environment/python.md
#374 対応。
> This reverts commit e397d74a8dc4a87124c21f4034fbd35e10e1afa6.
起動時に、
http://localhost:8000/homepage/
とならないケース、例えば　http://localhost:8000　では、不具合発生の可能性があるため。
また、 古い (=3.6以前) Python では、 -d が使えなので、念のため 3.6 以前用の記述は残しておく。
- おまけ
=> python.md を再修正

index.html
#369 : おめシス人気投票 中間発表 を追加
- おまけ
=> おめシス人気投票 中間発表 を追加

assets/i18n/resource.json, index.html
=> 人気投票セクション更新

.github/workflows/test.yml
- [actions/checkout](https://github.com/actions/checkout) を v2 に更新
- fetch depth によるパフォーマンス改善など
- [actions/cache](https://github.com/actions/cache) を使用
- cache による高速化
- yarn を直接使用
- yarn はインストールされているため ([インストール済みのソフトウェア](https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md))
- build を削除
- jest の実行に build は不要
- おまけ
- …
=> refactor: workflow のリファクタリング

pages/backup_announce_section.html
人気投票セクションのバックアップページを作成 (#387)
- おまけ
=> 人気投票セクションのバックアップページを作成 (#387)

assets/css/index.css, index.html, pages/pass200000sss.html
=> 20万登録者ページ追加

index.html, pages/pass200000sss.html
=> [更新] 21万登録者

pages/contributors.html
[コントリビュータ一覧のページ](https://omegasisters.github.io/homepage/pages/contributors.html)が正しく表示されていなかったので修正しました．
`contributor.author`がnullになっていたコントリビュータがいたのが原因だったため，ヌルチェックを挿入しました．
- おまけ
jsに疎いため，より効率的にnullを排除する方法があるかもしれないです．
=> contributorのページが正しく表示されない問題を修正

assets/css/index.css, pages/backup_announce_section.html
シンクロニティのページの picture の位置を修正 ( #397 )
**修正前 - PC**
**修正後 - PC**
**修正前 - スマホ**
**修正後 - スマホ**
- おまけ
詳細は、 #397 参照 (今から書く)。
=> シンクロニティのページの picture の位置を修正

index.html, pages/pass200000sss.html
チャンネル登録者数23万人突破，おめでとうございます！
関連ページを更新しました！
- おまけ
=> [更新] 23万登録者

index.html
#407 より
swiper.jsのバージョンを`latest`から`5.4.5`に固定。
変更前
変更後
- おまけ
=> swiper.jsのバージョンを固定

index.html, pages/pass200000sss.html
祝！登録者数24万人突破！
関連ページを更新しました
- おまけ
=> [更新] 24万登録者

index.html, pages/pass200000sss.html
登録者数フタゴー突破おめでとうございます！
ホームページを更新しました．
- おまけ
=> [更新]25万登録者

index.html, pages/pass200000sss.html
登録者数26万人&遅くなりましたが誕生日おめでとうございます！
ホームページを更新しました．
- おまけ
=> [更新] 26万人登録者

pages/pass200000sss.html
リオさんのYoutube登録者9000人記念ツイート、当時これだけ見つけられなくて、リオさんの分もレイさんのツイートで暫定的に補完していた。最近再捜索して、 https://twitter.com/omesis_rio/status/987253737151320064 を発見。文字だけツイートだったから見逃したっぽい。実際文字だけの記念ツイートはこれだけ。
おめシスはいいぞ。
- 修正前
- 修正後
- おまけ
=> リオさんの9000人登録記念tweet を適切なものに置き換え
